load("@rules_cc//cc:defs.bzl",  "cc_library")

cc_library(
    name = "libmemento",
    srcs = ["Editor.cpp", "History.cpp"],
    hdrs = ["EditorState.h", "Editor.h", "History.h"],
    visibility = ["//main:__pkg__"],
)
